# Generated by Django 3.0.6 on 2020-07-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CountITapp', '0002_auto_20200629_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='asset_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='equipment_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='equipment_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='service_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
