# Generated by Django 3.0.6 on 2020-07-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CountITapp', '0004_auto_20200701_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='asset_tag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='equipment_model',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='service_tag',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
