# Generated by Django 3.0.6 on 2020-07-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CountITapp', '0005_auto_20200701_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='comments',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
